-- GENERATED by C->Haskell Compiler, version 0.28.1 Switcheroo, 1 April 2016 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "src/Marshalling.chs" #-}
{-# LANGUAGE CPP, ForeignFunctionInterface #-}
{-# LANGUAGE FlexibleInstances #-}
module Marshalling where



-- import Foreign
-- import Foreign.C.Types

-- #include "/vagrant/src/online_matching.c"

-- data Vector a = Vector
--   { volume :: Int
--   , size :: Int
--   , array :: Ptr a
--   }

-- instance Storable (Vector Int) where
--     sizeOf _ = {#sizeof vector_int #}
--     alignment _ = {#alignof vector_int #}
--     peek p = Vector
--       <$> (fromIntegral <$> {#get vector_int->volume #} p)
--       <*> (fromIntegral <$> {#get vector_int->size #} p)
--       <*> (castPtr <$> {#get vector_int->array #} p)
--     poke p (Vector volume size array) = do
--       ({#set vector_int.volume #} p $ fromIntegral volume)
--       ({#set vector_int.size #} p $ fromIntegral size)
--       ({#set vector_int.array #} p $ castPtr array)

-- {#pointer *vector_int -> Vector Int nocode #}


-- data Result = Result
--   { positions :: Vector Int
--   , comparisons :: Int
--   }

-- instance Storable Result where
--   sizeOf _ = {#sizeof result #}
--   alignment _ = {#alignof result #}
--   peek p = Result
--     <$> ({#get result->positions #} p)
--     <*> (fromIntegral <$> {#get result->comparisons #} p)
--   poke p (Result positions comparisons) = do
--     ({#set result.positions #} p positions)
--     ({#set result.comparisons #} p $ fromIntegral comparisons)

-- {#pointer *result -> Result nocode #}
